image: docker/compose:latest

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:dind
      
before_script:
  - apk add --update curl jq python3 py-pip
  - pip install awscli
  - docker version
  - docker-compose version

build:
  script:
    - docker-compose down
    - docker-compose build
    
  tags:
    - ECICL-CICD
